version: 2.1

jobs:
  test:
    parameters:
      tag:
        type: string
    docker:
      - image: kelvintaywl/ci-128877:<< parameters.tag >>
    resource_class: large
    steps:
      - checkout

workflows:
  main:
    jobs:
      - test:
          name: failed
          tag: latest
      - test:
          name: succeeded
          tag: success
