version: 2.1

parameters:
  service:
    type: string
    default: "foobar"

jobs:
  tar:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
workflows:
  <<pipeline.parameters.service>>-main:
    jobs:
      - tar
